config/routes.rb
Cookery::Application.routes.draw do
  devise_for :users

  root 'recipes#index'

  resources :recipes do
    collection do
      get 'search'
    end
  end

  resources :categories, only: ['create']

  resources :ingredients, only: ['index', 'create']

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base

  include IsNamed

  belongs_to :author, class_name: User, foreign_key: 'user_id'
  validates_presence_of :author

  validates_numericality_of :servings, greater_than: 0

  has_and_belongs_to_many :categories

  has_many :pictures, dependent: :destroy
  accepts_nested_attributes_for :pictures

  has_many :steps
  accepts_nested_attributes_for :steps, reject_if: :all_blank, allow_destroy: true

  has_many :videos
  accepts_nested_attributes_for :videos, reject_if: :all_blank, allow_destroy: true

  # Difficulty
  DIFFICULTY_LEVELS = %w(easy medium difficult).freeze
  validates_inclusion_of :difficulty, in: DIFFICULTY_LEVELS

  def self.difficulty_levels
    DIFFICULTY_LEVELS
  end

  def picture
    if pictures.any?
      pictures.first
    else
      Picture.new
    end
  end

  def duration
    steps.map(&:duration).reduce(0, &:+)
  end

  def ingredients
    steps.map(&:ingredients).flatten.uniq
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :convert_duration, only: [:create, :update]
  before_action :check_ingredients, only: [:create, :update]

  load_and_authorize_resource except: [:index]

  # GET /recipes
  def index
    authorize! :index, Recipe
    @recipes = Recipe.order(sort_parameters).page(params[:page])
  end

  # GET /recipes/1
  def show
  end

  # GET /recipes/new
  def new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  def create
    @recipe.author = current_user

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  # PATCH/PUT /recipes/1
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  def search
    authorize! :index, Recipe
    @recipes = Recipe.where('name like ?', "%#{params[:search]}%").order(sort_parameters).page(params[:page])
    render 'index.html'
  end

  # DELETE /recipes/1
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url }
    end
  end

  private

  def recipe_params
    add_extra_categories

    params.require(:recipe).permit(:name, :difficulty, :pictures, :servings,
      category_ids: [],
      steps_attributes: [:id, :_destroy, :name, :duration, :notes,
        quantities_attributes: [:id, :_destroy, :ingredient_id, :ingredient, :amount, :unit,
        ]
      ],
      videos_attributes: [:id, :_destroy, :url],
      pictures_attributes: [:id, :_destroy, :photo]
    )
  end

  def add_extra_categories
    if params[:'extra-category']
      categories = params[:'extra-category'].split(/[ ,]/).map(&:strip).delete_if(&:blank?)
      categories = categories.map { |c| Category.where(name: c).first_or_create.id }
      params[:recipe][:category_ids] += categories
    end
  end

  def convert_duration
    if params[:recipe] && params[:recipe][:steps_attributes]
      params[:recipe][:steps_attributes].each_value do |s|
        s[:duration] = "#{s[:duration].to_i.minutes}" unless s[:duration].blank?
      end
    end
  end

  def check_ingredients
    return unless params[:recipe] && params[:recipe][:steps_attributes]

    params[:recipe][:steps_attributes].each_value do |step|
      next unless step[:quantities_attributes]

      step[:quantities_attributes].each_value do |quantity|
        if quantity[:ingredient_id].blank? && !quantity[:ingredient].blank?
          quantity[:ingredient_id] = Ingredient.where(name: quantity[:ingredient]).first_or_create.id
        end
        quantity.delete :ingredient
      end
    end
  end

  def sort_parameters
    direction = params[:direction] == 'desc' ? 'desc' : 'asc'
    "lower(name) #{direction}"
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
  def main_picture_tag(recipe, size = :medium)
    picture_tag recipe.picture, size
  end

  def picture_tag(picture, size = :medium)
    image_tag picture.photo.url(size), class: 'img-rounded img-responsive'
  end

  def difficulty_tag(difficulty, options = {})
    options = { class: '' }.merge(options)
    to_label = {
      'easy' => 'success',
      'medium' => 'warning',
      'difficult' => 'danger'
    }
    to_icon = {
      'easy' => 'glyphicon glyphicon-thumbs-up',
      'medium' => '',
      'difficult' => 'glyphicon glyphicon-thumbs-down'
    }

    content_tag(:span, class: "difficulty label label-#{to_label[difficulty]} #{options[:class]}") do
      content_tag(:span, difficulty) +
      content_tag(:i, '', class: to_icon[difficulty])
    end
  end

  def amount_tag(amount, unit)
    unit = unit.pluralize if amount > 1
    content_tag(:span,
      "#{amount} #{unit}",
      class: 'amount'
    )
  end

  def duration_tag(duration, options = {})
    options = { class: '' }.merge(options)
    content_tag(:div, class: "duration small-boxed pull-right #{options[:class]}") do
      content_tag(:span, distance_of_time_in_words(duration)) +
      content_tag(:i, '', class: 'glyphicon glyphicon-time')
    end
  end

  def add_association_button(f, association)
    link_to_add_association f, association, class: 'btn btn-success',
                            force_non_association_create: f.object.send(association).any?,
                            'data-association-insertion-traversal' => 'siblings',
                            'data-association-insertion-node' => ".#{association}",
                            'data-association-insertion-method' => 'append' do
      content_tag(:i, '', class: 'icon-plus-sign icon-white') +
      association.to_s.singularize.titlecase
    end
  end
end

app/views/recipes/_form.html.haml
= simple_form_for @recipe, html: { multipart: true } do |f|

  %fieldset.row-fluid.boxed.shadow.presentation
    .span4.pictures-container

      = add_association_button f, :pictures

      = f.simple_fields_for :pictures do |picture|
        = render 'picture_fields', f: picture

    .span8
      .row-fluid
        .span8
          = f.input :name, autofocus: true
        .span4
          = duration_tag(@recipe.duration)
      .row-fluid
        = f.association :categories, collection: Category.order(:name).load, input_html: { rel: 'tooltip', 'data-toogle' => 'tooltip', 'data-placement' => 'right', 'data-original-title' => 'Select one or multiple categories from the list'}
        = text_field_tag :'extra-category', nil, placeholder: 'Extra: Category1, Category2, Category3', class: 'controls string', rel: 'tooltip', 'data-toggle' => 'tooltip', 'data-placement' => 'right', 'data-original-title' => 'Add extra categories by writing them here'
      .row-fluid
        = f.input :difficulty, collection: Recipe.difficulty_levels, default: 1
      .row-fluid
        = f.input :servings, default: 1

  .boxed.shadow.steps-container
    %h2 Steps

    = add_association_button f, :steps

    %hr

    .steps
      = f.simple_fields_for :steps do |step|
        = render 'step_fields', f: step

  .boxed.shadow.videos-container
    %h3
      Videos

    = add_association_button f, :videos

    %hr

    .videos
      = f.simple_fields_for :videos do |video|
        = render 'video_fields', f: video

  .boxed.shadow
    .row-fluid
      .span5
      .span7
        = button_tag type: :submit, class: 'controls btn btn-primary' do
          %i.icon-ok.icon-white
          Save
        = link_to recipes_path, class: 'btn' do
          %i.icon-remove
          Back

app/views/recipes/_list_view.html.haml
%ul.list-unstyled
  - recipes.each do |recipe|
    %li
      .row{ 'data-link' => recipe_path(recipe)}
        .col-sm-2.col-xs-3
          = main_picture_tag recipe, :thumb
        .col-sm-10.col-xs-9
          %h4.btn-link= recipe.name

app/views/recipes/_picture.html.haml
- if @recipe.pictures.length > 1
  #carousel.carousel.slide
    -# Pointers
    %ol.carousel-indicators
      - @recipe.pictures.each_index do |index|
        %li{ 'data-target' => '#carousel', 'data-slide-to' => "#{index}", class: ('active' if index == 0) }

    -# Pictures
    .carousel-inner
      - @recipe.pictures.each_with_index do |picture, index|
        .item{ class: ('active' if index == 0) }
          = picture_tag picture
          - if picture.caption.present?
            .carousel-caption
              %h4= picture.caption
    -# Arrows
    = link_to '#carousel', class: 'carousel-control left', 'data-slide' => 'prev' do
      %span.glyphicon.glyphicon-chevron-left
    = link_to '#carousel', class: 'carousel-control right', 'data-slide' => 'next' do
      %span.glyphicon.glyphicon-chevron-right
- else
  = main_picture_tag @recipe

app/views/recipes/_picture_fields.html.haml
.nested-fields.video
  .control-group
    .controls.form-inline
      = f.input :photo, as: :picture
      = link_to_remove_association f, class: 'pull-right' do
        %i.icon-remove

app/views/recipes/_quantity_fields.html.haml
%fieldset.nested-fields.boxed.quantity
  .control-group
    .controls.form-inline
      = f.input_field :ingredient, placeholder: 'Ingredient...', label: false, class: 'ingredient_picker', autocomplete: 'off'
      = f.hidden_field :ingredient_id, class: 'ingredient_picker_id'
      = f.input_field :amount, type: 'number', label: false, class: 'short-input'
      = f.input_field :unit, collection: Quantity.units, default: 1, label: false, class: 'short-input'
      = link_to_remove_association f, class: 'pull-right' do
        %i.icon-remove

app/views/recipes/_step_fields.html.haml
%fieldset.nested-fields.row-fluid.boxed.shadow.step
  = link_to_remove_association f, class: 'pull-right' do
    %i.icon-remove

  .row-fluid
    .span6
      %h3= f.input :name
    .span6
      = f.input :duration, wrapper: 'append' do
        = f.input_field :duration, type: 'number', class: 'span9 duration-input'
        %span.add-on minutes

  .row-fluid
    .span6.quantities-container
      %h4 Ingredients

      = add_association_button f, :quantities

      %hr

      .quantities
        = f.simple_fields_for :quantities do |quantity|
          = render 'quantity_fields', f: quantity

    .span6
      = f.input :notes, input_html: { rows: 5 }

app/views/recipes/_video_fields.html.haml
%fieldset.nested-fields.boxed.video
  .control-group
    .controls.form-inline
      = f.input_field :url, class: 'video-input', placeholder: 'URL: https://youtube.com/...', type: 'url'
      %span.video-output
      = link_to_remove_association f, class: 'pull-right' do
        %i.icon-remove

app/views/recipes/edit.html.haml
= content_for :well do
  %h1 Editing Recipe

= render 'form'

app/views/recipes/index.html.haml
= content_for :main_css, 'recipes-list'
= content_for :well do

  - if params[:search]
    .row= "Displaying search results for *#{params[:search]}*"

  .row
    .col-md-8.col-sm-8.col-xs-6
      %h2= "Recipes"

.row
  .col-md-8.col-xs-12
    = render 'list_view', recipes: @recipes

%br

%div.text-center= page_entries_info @recipes
= paginate @recipes

app/views/recipes/new.html.haml
= content_for :well do
  %h1 New Recipe

= render 'form'

app/views/recipes/show.html.haml
= content_for :title do
  = "Recipe - #{@recipe.name}"

= content_for :well do
  - if can? :edit, Recipe
    = link_to edit_recipe_path(@recipe), class: 'btn btn-large btn-primary' do
      %i.glyphicon.glyphicon-edit.icon-white
      Edit Recipe
  - if can? :destroy, Recipe
    = link_to recipe_path(@recipe), method: :delete, confirm: 'Are you sure?', class: 'btn btn-large btn-danger' do
      %i.glyphicon.glyphicon-remove
      Remove Recipe

%section.container-fluid
  .row.boxed.shadow.presentation
    .col-md-4.col-sm-6
      = render 'picture'

    .col-md-8.col-sm-6
      .row
        .col-md-8.col-sm-7
          %h2.title= @recipe.name
        .col-md-4.col-sm-5.hidden-xs
          = duration_tag(@recipe.duration)
      .row
        - if @recipe.categories.any?
          %h4 Categories
          - @recipe.categories.each do |category|
            %span.label.label-info= category.name
      .row
        %h4 Difficulty
        = difficulty_tag(@recipe.difficulty)
      .row
        %h4= "Servings: #{@recipe.servings}"

  %section.row.boxed.shadow.accordion.steps-container
    %h2 Steps
    %hr

    - @recipe.steps.each_with_index do |step,index|
      %section.boxed.shadow.accordion-group.step
        .row.accordion-heading
          .col-md-8
            = link_to "#collapse#{index}", class: 'accordion-toggle', 'data-toggle' => 'collapse' do
              %h3= step.name
          .col-md-4.hidden-xs= duration_tag(step.duration)

        .row.collapse.accordion-body.in{ id: "collapse#{index}" }
          .accordion-inner
            .col-md-6.col-sm-6
              - if step.quantities.any?
                %h4 Ingredients
                - step.quantities.each do |quantity|
                  .row.ingredient
                    .col-md-6.col-sm-6.col-xs-6= quantity.ingredient.name
                    - if quantity.unit.present?
                      .col-md-6.col-sm-6.col-xs-6= amount_tag(quantity.amount, quantity.unit)

            .col-md-6.col-sm-6
              - if step.notes.present?
                %h4 Notes
                = simple_format(step.notes)

  - if @recipe.videos.any?
    %section.row.boxed.shadow.videos-container
      %h2 Videos
      %hr

      %ul.thumbnails
        - @recipe.videos.each do |video|
          %li.col-md-4.col-sm-6
            .boxed.video= youtube_video video.url