config/routes.rb
Cookery::Application.routes.draw do
  devise_for :users

  root 'recipes#index'

  resources :recipes do
    collection do
      get 'search'
    end
  end

  resources :categories, only: ['create']

  resources :ingredients, only: ['index', 'create']

end

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{ class: "alert #{bootstrap_class_for(name)} fade in"}
      %a.close{'data-dismiss' => 'alert'} ×
      = content_tag :div, msg, id: "flash_#{name}"

app/views/layouts/_navigation.html.haml
.navbar-header
  = button_tag type: 'button', class: 'navbar-toggle collapsed', 'data-toggle' => 'collapse', 'data-target' => '#collapsable-navbar' do
    %span.sr-only= "Toggle Navigation"
    %span.icon-bar
    %span.icon-bar
    %span.icon-bar

  = link_to 'Cookery', root_path, class: 'navbar-brand'

#collapsable-navbar.navbar-collapse.collapse
  %ul.nav.navbar-nav
    %li.dropdown.active
      = link_to '#', class: 'dropdown-toggle', 'data-toggle' => 'dropdown' do
        Recipes
        %strong.caret

      %ul.dropdown-menu
        %li= link_to 'See recipes', recipes_path
        - if can? :create, Recipe
          %li= link_to 'Add recipe', new_recipe_path

  = form_tag search_recipes_path, method: 'get', class: 'navbar-form navbar-left' do
    = text_field_tag :search, nil, placeholder: 'Search for recipes...', class: 'form-control'

  %ul.nav.navbar-nav.navbar-right
    - if user_signed_in?
      %li= link_to "#{current_user.email}", '#'
      %li= link_to 'Sign out', destroy_user_session_path, method: :delete
    - else
      %li= link_to 'Sign up', new_user_registration_path
      %li.dropdown
        = link_to '#', class: 'dropdown-toggle', 'data-toggle' => 'dropdown' do
          Sign In
          %strong.caret

        .dropdown-menu
          = render 'devise/sessions/form', extra_class: 'popup-form', resource: User.new, resource_name: 'user'

app/views/layouts/_well.html.haml
%section.well
  .container-fluid
    = yield(:well)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ charset: 'utf-8' }
    %meta{ name: 'viewport', content: 'width=device-width, initial-scale=1, maximum-scale=1' }
    %title= content_for?(:title) ? yield(:title) : 'Cookery'
    %meta{ content: '', name: 'description' }
    %meta{ content: '', name: 'author' }
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
    = yield(:head)

  %body

    %nav.navbar.navbar-default.navbar-fixed-top.navbar-inverse
      .container-fluid
        = render 'layouts/navigation'

    %section#main{ role: 'main', class: "#{content_for?(:main_css) ? yield(:main_css) : ''}" }
      .container-fluid
        = render 'layouts/messages'
        = render 'layouts/well'
        = yield

        %footer